---
- name: Setup Slave
  hosts: all
  become: true
  roles:
    - geerlingguy.docker
    # - geerlingguy.jenkins
    # - geerlingguy.nodejs
  tasks:
     - name: Add APT repository for Java
       apt_repository:
         repo: 'ppa:linuxuprising/java'
         state: present

     - name: Update APT package lists
       apt:
         update_cache: yes

     - name: Install Java 17
       apt:
         name: openjdk-17-jdk
         state: present
  
